let listaDeLibros = [
    {
      id: 1,
      titulo: "Rapido y Furioso",
      autor: "F. Scott Briman",
      genero: "Accion",
      anoPublicacion: 1925,
      idioma: "Español",
      precio: 15.99,
    },
    {
      id: 2,
      titulo: "Un Verano Para Siempre",
      autor: "Gabriela Garcia ",
      genero: "Romance",
      anoPublicacion: 1967,
      idioma: "Español",
      precio: 19.99,
    },
    {
      id: 3,
      titulo: "Gerra de Reveldes",
      autor: "Harper Lee",
      genero: "Ficcion",
      anoPublicacion: 1960,
      idioma: "Español",
      precio: 12.5,
    },
    {
      id: 4,
      titulo: "2012",
      autor: "Danien Fostert",
      genero: "Ciencia ficcion",
      anoPublicacion: 1949,
      idioma: "Inglés",
      precio: 14.99,
    },
  ];